[package]
name = "blst_eip2537"
version = "0.1.0"
authors = ["sean-sn <sean@supranational.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#blst = "0.2.0"
hex = "0.4"
csv = "1"

[build-dependencies]
cc = "1.0"
